/**
 * Mapping paese (italiano + inglese) → emoji bandiera.
 * Non esaustivo: fallback a "🌍" se non trovato.
 */
const FLAGS: Record<string, string> = {
  // Nomi italiani (principali)
  "italia": "🇮🇹",
  "francia": "🇫🇷",
  "germania": "🇩🇪",
  "spagna": "🇪🇸",
  "regno unito": "🇬🇧",
  "gran bretagna": "🇬🇧",
  "inghilterra": "🇬🇧",
  "stati uniti": "🇺🇸",
  "canada": "🇨🇦",
  "messico": "🇲🇽",
  "brasile": "🇧🇷",
  "argentina": "🇦🇷",
  "colombia": "🇨🇴",
  "cile": "🇨🇱",
  "perù": "🇵🇪",
  "australia": "🇦🇺",
  "nuova zelanda": "🇳🇿",
  "giappone": "🇯🇵",
  "corea del sud": "🇰🇷",
  "corea": "🇰🇷",
  "cina": "🇨🇳",
  "india": "🇮🇳",
  "hong kong": "🇭🇰",
  "taiwan": "🇹🇼",
  "singapore": "🇸🇬",
  "thailandia": "🇹🇭",
  "vietnam": "🇻🇳",
  "indonesia": "🇮🇩",
  "filippine": "🇵🇭",
  "svizzera": "🇨🇭",
  "austria": "🇦🇹",
  "belgio": "🇧🇪",
  "paesi bassi": "🇳🇱",
  "olanda": "🇳🇱",
  "lussemburgo": "🇱🇺",
  "portogallo": "🇵🇹",
  "irlanda": "🇮🇪",
  "scozia": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "danimarca": "🇩🇰",
  "svezia": "🇸🇪",
  "norvegia": "🇳🇴",
  "finlandia": "🇫🇮",
  "islanda": "🇮🇸",
  "polonia": "🇵🇱",
  "cechia": "🇨🇿",
  "repubblica ceca": "🇨🇿",
  "slovacchia": "🇸🇰",
  "ungheria": "🇭🇺",
  "romania": "🇷🇴",
  "bulgaria": "🇧🇬",
  "grecia": "🇬🇷",
  "cipro": "🇨🇾",
  "turchia": "🇹🇷",
  "croazia": "🇭🇷",
  "slovenia": "🇸🇮",
  "serbia": "🇷🇸",
  "bosnia": "🇧🇦",
  "bosnia ed erzegovina": "🇧🇦",
  "macedonia": "🇲🇰",
  "macedonia del nord": "🇲🇰",
  "montenegro": "🇲🇪",
  "albania": "🇦🇱",
  "kosovo": "🇽🇰",
  "ucraina": "🇺🇦",
  "bielorussia": "🇧🇾",
  "lituania": "🇱🇹",
  "lettonia": "🇱🇻",
  "estonia": "🇪🇪",
  "russia": "🇷🇺",
  "georgia": "🇬🇪",
  "armenia": "🇦🇲",
  "azerbaigian": "🇦🇿",
  "israele": "🇮🇱",
  "palestina": "🇵🇸",
  "libano": "🇱🇧",
  "siria": "🇸🇾",
  "giordania": "🇯🇴",
  "iran": "🇮🇷",
  "iraq": "🇮🇶",
  "arabia saudita": "🇸🇦",
  "emirati arabi uniti": "🇦🇪",
  "qatar": "🇶🇦",
  "kuwait": "🇰🇼",
  "egitto": "🇪🇬",
  "marocco": "🇲🇦",
  "tunisia": "🇹🇳",
  "algeria": "🇩🇿",
  "sudafrica": "🇿🇦",
  "nigeria": "🇳🇬",
  "kenya": "🇰🇪",
  "etiopia": "🇪🇹",
  "ghana": "🇬🇭",
  "senegal": "🇸🇳",

  // Nomi inglesi (per compatibilità import multilingua)
  "italy": "🇮🇹",
  "france": "🇫🇷",
  "germany": "🇩🇪",
  "spain": "🇪🇸",
  "united kingdom": "🇬🇧",
  "uk": "🇬🇧",
  "england": "🇬🇧",
  "united states": "🇺🇸",
  "usa": "🇺🇸",
  "us": "🇺🇸",
  "mexico": "🇲🇽",
  "brazil": "🇧🇷",
  "chile": "🇨🇱",
  "peru": "🇵🇪",
  "new zealand": "🇳🇿",
  "japan": "🇯🇵",
  "south korea": "🇰🇷",
  "korea": "🇰🇷",
  "china": "🇨🇳",
  "switzerland": "🇨🇭",
  "belgium": "🇧🇪",
  "netherlands": "🇳🇱",
  "luxembourg": "🇱🇺",
  "portugal": "🇵🇹",
  "ireland": "🇮🇪",
  "denmark": "🇩🇰",
  "sweden": "🇸🇪",
  "norway": "🇳🇴",
  "finland": "🇫🇮",
  "iceland": "🇮🇸",
  "poland": "🇵🇱",
  "czech republic": "🇨🇿",
  "czechia": "🇨🇿",
  "slovakia": "🇸🇰",
  "hungary": "🇭🇺",
  "greece": "🇬🇷",
  "cyprus": "🇨🇾",
  "turkey": "🇹🇷",
  "croatia": "🇭🇷",
  "ukraine": "🇺🇦",
  "lithuania": "🇱🇹",
  "latvia": "🇱🇻",
  "israel": "🇮🇱",
  "lebanon": "🇱🇧",
  "jordan": "🇯🇴",
  "egypt": "🇪🇬",
  "morocco": "🇲🇦",
  "south africa": "🇿🇦",
};

export function countryFlag(country: string | null | undefined): string {
  if (!country) return "🌍";
  const key = country.trim().toLowerCase();
  return FLAGS[key] || "🌍";
}
