[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "poppler_utils"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = [
  "sed -i 's/provider = \"sqlite\"/provider = \"postgresql\"/' prisma/schema.prisma",
  "npm run build"
]

[start]
cmd = "npm run start"
